version: '3.8'
services:
  db:
    image: mydb
    ports:
      - "3360:3360"
    environment:
      - MYSQL_ROOT_PASSWORD=adsw1423@g
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=shopdb
  back:
    image: back
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=db
    depends_on:
      - db
    volumes:
      - ./backend:/shopApp/
  front:
    image: front
    command: yarn run start
    ports:
      - "3000:3000"
    volumes:
      - ./client:/docshopApp/
