FROM mysql

ENV MYSQL_ROOT_PASSWORD=adsw1423@g

ENV MYSQL_DATABASE=shopdb

# ENV POSTGRES_PASSWORD 1z2x12@as!q

# ENV POSTGRES_USER deopi

# ENV POSTGRES_DB shopdb

COPY dump.sql /docker-entrypoint-initdb.d/

EXPOSE 3360