# Generated by Django 4.2.1 on 2023-08-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=99.99, max_digits=7)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Done'), (2, 'Error')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True, max_length=500)),
                ('what_product', models.CharField(choices=[('CLOTHES', (('T-SHIRTS', 'T-shirt'), ('HOODIES', 'Hoodie'), ('JACKETS', 'Jacket'), ('COATS', 'Coat'), ('SWEATSHIRTS', 'Sweatshirt'), ('SWEATERS', 'Sweater'), ('JEANS', 'Jeans'))), ('SHOES', (('SNEAKERS', 'Sneakers'), ('SHOES', 'Shoes'), ('HEELS', 'Heels'), ('BOOTS', 'Boots')))], default='NOTYPE', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=99.99, max_digits=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
