# Generated by Django 4.1.10 on 2023-11-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
    ]
