# Generated by Django 4.2.1 on 2023-08-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_product_favorites_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
