# Generated by Django 4.2.1 on 2023-08-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(default='Pending', editable=False, null=True),
        ),
    ]
