# Generated by Django 4.2.1 on 2023-08-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='user',
            new_name='user_id',
        ),
    ]
