# Generated by Django 4.2.1 on 2023-08-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_product_what_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='what_product',
            new_name='category',
        ),
    ]
