# Generated by Django 4.2.1 on 2023-08-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_rename_basketitem_cartitem_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
