# Generated by Django 4.2.1 on 2023-08-11 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_order_price_remove_order_product_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
