# Generated by Django 4.2.1 on 2023-08-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_product_what_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='what_product',
            field=models.CharField(blank=True, choices=[(None, ''), ('SNEAKERS', 'Sneakers'), ('HOODIES', 'Hoodies')], max_length=30),
        ),
    ]
