# Generated by Django 4.2.1 on 2023-08-16 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0028_alter_basketitem_id_alter_favorite_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasketItem',
            new_name='CartItem',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Awaiting payment'), (2, 'Awaiting fulfillment'), (3, 'Awaiting shipment'), (4, 'Partially shipped'), (5, 'Completed'), (6, 'Shipped'), (7, 'Cancelled'), (8, 'Declined'), (9, 'Refunded'), (10, 'Disputed')], default=0),
        ),
    ]
